### ISSUE TITLE
cannot run.

### ISSUE THREAD

**Issue by heroku-miraheze** [satdreamgr/dabstreamer#1]
File "/usr/bin/dabstreamer", line 33
    _, sref, pid, sid = parameters
TabError: inconsistent use of tabs and spaces in indentation

**Comment by heroku-miraheze** [comment]
Traceback (most recent call last):
  File "/usr/bin/./dabstreamer", line 275, in <module>
    daemon.start()
  File "/usr/bin/./dabstreamer", line 206, in start
    pf = file(self.pidfile,"r")
NameError: name 'file' is not defined

**Comment by athoik** [comment]
Thanks! 

Changed all tabs to spaces: https://github.com/satdreamgr/dabstreamer/commit/b6dff15d2e2a36b68e4f65ab38c7b822a53f8ff3

**Comment by heroku-miraheze** [comment]
@athoik Traceback (most recent call last):
File "/usr/bin/./dabstreamer", line 275, in
daemon.start()
File "/usr/bin/./dabstreamer", line 206, in start
pf = file(self.pidfile,"r")
NameError: name 'file' is not defined

**Comment by athoik** [comment]
Closing #1 resolved via https://github.com/satdreamgr/dabstreamer/commit/b6dff15d2e2a36b68e4f65ab38c7b822a53f8ff3
