### ISSUE TITLE
cannot run #2

### ISSUE THREAD

**Issue by heroku-miraheze** [satdreamgr/dabstreamer#2]
Traceback (most recent call last):
File "/usr/bin/./dabstreamer", line 275, in
daemon.start()
File "/usr/bin/./dabstreamer", line 206, in start
pf = file(self.pidfile,"r")
NameError: name 'file' is not defined

**Comment by athoik** [comment]
Thanks,

File is not available on python3, replaced with open: https://github.com/satdreamgr/dabstreamer/commit/e3cf67170e3d3809ef79c6de08c3c5f5b35fabff

**Comment by heroku-miraheze** [comment]
Still in the same problem.

**Comment by heroku-miraheze** [comment]
#3

**Comment by athoik** [comment]
Ok, now should be better: https://github.com/satdreamgr/dabstreamer/commit/47fb43172f0ca20a1f14ee22014b0d5ba33fdc2f
